import re, sys
from pathlib import Path
RULES = {'E01': 'emotion feeling tension relief wonder', 'E02': 'expectation surprise unfair twist', 'E03': 'theme fiction mechanics narrative', 'E04': 'emergence rules systems complexity', 'E05': 'ai readable random state feedback', 'E06': 'difficulty challenge fail death skill', 'E07': 'failure retry checkpoint frustration', 'E08': 'onboarding beginner expert mastery', 'E09': 'agency choice quest narrative', 'E10': 'character story quest reward consistency', 'E11': 'world environment storytelling lore', 'E12': 'decision strategy choice dominant', 'E13': 'information hidden uncertainty fog', 'E14': 'flow pacing rhythm overload', 'E15': 'fairness unfair telegraph counterplay', 'E16': 'balance meta build winrate', 'E17': 'multiplayer team cooperation griefing', 'E18': 'pvp bluff competitive prediction', 'E19': 'reward loot dopamine retention', 'E20': 'remorse grind monetization regret', 'E21': 'ui hud signal noise attention', 'E22': 'cue audio visual animation ui', 'E23': 'guidance tutorial waypoint immersion', 'E24': 'input control latency responsiveness', 'E25': 'market audience positioning differentiation', 'E26': 'marketing onboarding promise expectation', 'E27': 'prototype playtest iteration hypothesis', 'E28': 'greybox prototype polish production', 'E29': 'data research telemetry interview evidence', 'E30': 'dependency architecture ai pipeline rework', 'E31': 'risk architecture irreversible decision', 'E32': 'team ownership communication handoff', 'E33': 'milestone morale progress team', 'E34': 'second order consequence tradeoff leadership', 'E35': 'retrospective feedback culture candor', 'E36': 'learning assumption unknown research', 'E37': 'ai npc behavior tree intent target', 'E38': 'ai error fallback hallucination failure', 'E39': 'companion ally cover coordination', 'E40': 'llm npc memory dialogue natural language'}
text = Path(sys.argv[1]).read_text(encoding='utf-8').lower() if len(sys.argv)>1 else sys.stdin.read().lower()
ranked=[]
for lens, words in RULES.items():
    score=sum(len(re.findall(re.escape(word.lower()), text)) for word in words.split())
    ranked.append((score,lens))
for score,lens in sorted(ranked,reverse=True)[:5]: print(f'{lens}\t{score}')
